Parameters:
    myVPC:
      Description: VPC used to deploy our resources below
      Type: AWS::EC2::VPC::Id
      ParameterProperty: vpc-9b9aa2e3
    PublicSubnet:
      Description: Subnet to be used for our Web Server
      Type: AWS::EC2::Subnet::Id
      ParameterProperty: subnet-b69e28fc
    AMItoUse:
      Description: AMI to use for our base Image
      Type: String
      ParameterProperty: ami-0dc8f589abe99f538
Resources:
  myWebAccessSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow http to our test host
      VpcId: !Ref myVPC
  myWebServerInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t3.micro
      ImageId: !Ref AMItoUse
      NetworkInterfaces:
        - AssociatePublicIpAddress: true
          DeviceIndex: 0
          GroupSet:
            - Ref: MyWebAccessSecurityGroup
          SubnetId: !Ref PublicSubnet
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          sudo yum update -y
          sudo yum install -y httpd
          sudo systemctl start httpd
          sudo systemctl enable httpd